services:
  postgres:
    image: postgres
    container_name: weather-data-service-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}  # Ensure that DB_NAME is defined in the .env file or environment
      POSTGRES_USER: ${DB_USERNAME}  # Ensure that DB_USERNAME is defined
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Ensure that DB_PASSWORD is defined
    ports:
      - '5432:5432'  # Exposes the PostgreSQL port to your host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data using a Docker volume

volumes:
  postgres_data:
    # Define volume storage if needed (optional)